"""PostgreSQL verification harness: project generation, preflight, view/compare/cleanup."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from dbt_refmerge.artifacts import ManifestNodeModel, load_manifest
from dbt_refmerge.domain import (
    IdentifierIdentity,
    ReasonCode,
    RelationIdentity,
    ScratchBoundary,
)
from dbt_refmerge.errors import ScratchBoundaryError, VerificationError
from dbt_refmerge.workspace import RunWorkspace

BASELINE_ALIAS_PREFIX = "dbt_refmerge_baseline_"
CANDIDATE_ALIAS_PREFIX = "dbt_refmerge_candidate_"
# Relations dbt-postgres may leave behind while (re)creating a view.
DBT_INTERMEDIATE_SUFFIXES = ("__dbt_tmp", "__dbt_backup")
SCRATCH_SCHEMA_VAR = "dbt_refmerge_scratch_schema"
HARNESS_PROJECT_NAME = "dbt_refmerge_harness"

FORBIDDEN_SCHEMAS = {"pg_catalog", "information_schema", "pg_toast", "pg_temp_1"}


def normalize_pg_ident(text: str, quoted: bool) -> IdentifierIdentity:
    return IdentifierIdentity(value=text if quoted else text.lower())


# PostgreSQL silently truncates identifiers longer than NAMEDATALEN - 1 bytes.
PG_MAX_IDENTIFIER_BYTES = 63


def validate_scratch_schema(schema: str, model_schema: str | None = None) -> IdentifierIdentity:
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_$]*", schema):
        quoted = False
        value = schema
    elif re.fullmatch(r'"(?:[^"\x00]|"")+"', schema):
        quoted = True
        value = schema[1:-1].replace('""', '"')
    else:
        raise ScratchBoundaryError(f"invalid scratch schema: {schema!r}")
    ident = normalize_pg_ident(value, quoted)
    if len(ident.value.encode("utf-8")) > PG_MAX_IDENTIFIER_BYTES:
        raise ScratchBoundaryError(f"scratch schema exceeds {PG_MAX_IDENTIFIER_BYTES} bytes: {schema!r}")
    if ident.value.lower() in FORBIDDEN_SCHEMAS:
        raise ScratchBoundaryError(f"scratch schema forbidden: {schema}")
    if model_schema is not None and ident.value.lower() == model_schema.lower():
        raise ScratchBoundaryError("scratch schema must differ from model output schema")
    return ident


def _sanitize_run_token(run_id: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", run_id.lower())[-16:]


def relation_token(run_id: str, model_unique_id: str) -> str:
    """Per-run, per-model suffix for scratch relation names (48-60 bytes with prefixes and dbt suffixes)."""
    return f"{_sanitize_run_token(run_id)}_{hashlib.sha256(model_unique_id.encode('utf-8')).hexdigest()[:8]}"


def scratch_identifiers(token: str) -> tuple[str, ...]:
    """Every relation name a harness run with ``token`` can create, including dbt intermediates."""
    names = []
    for prefix in (BASELINE_ALIAS_PREFIX, CANDIDATE_ALIAS_PREFIX):
        names.append(f"{prefix}{token}")
        names.extend(f"{prefix}{token}{suffix}" for suffix in DBT_INTERMEDIATE_SUFFIXES)
    return tuple(names)


HARNESS_MODELS_BASELINE = """{{ config(alias='%s', materialized='view') }}\n\n{%% raw %%}\n%s\n{%% endraw %%}\n"""

# Every harness relation lands in the validated scratch schema, passed as a --vars JSON value so the
# schema name never has to be embedded in Jinja.
GENERATE_SCHEMA_NAME_MACRO = (
    "{% macro generate_schema_name(custom_schema_name, node) -%}\n"
    f"    {{{{ var('{SCRATCH_SCHEMA_VAR}') }}}}\n"
    "{%- endmacro %}\n"
)

# Runs one SQL statement generated by dbt-refmerge and prints its rows between nonce markers, every
# value as a string (agate returns Decimal, which tojson cannot encode). The SQL arrives through
# run-operation --args, which dbt does not render as Jinja.
QUERY_MACRO = """{% macro dbt_refmerge_query(nonce, sql, statement_timeout_ms, label='') %}
  {% do run_query('set statement_timeout = ' ~ (statement_timeout_ms | int)) %}
  {% set table = run_query(sql) %}
  {% set rows = [] %}
  {% for row in table.rows %}
    {% set values = [] %}
    {% for value in row.values() %}
      {% do values.append(none if value is none else (value | string)) %}
    {% endfor %}
    {% do rows.append(values) %}
  {% endfor %}
  {{ print('DBT_REFMERGE_RESULT_' ~ nonce ~ '_BEGIN') }}
  {{ print(tojson({'columns': table.column_names | list, 'rows': rows})) }}
  {{ print('DBT_REFMERGE_RESULT_' ~ nonce ~ '_END') }}
{% endmacro %}
"""

# Drops only views, only in the given schema, only with the given names.
DROP_VIEWS_MACRO = """{% macro dbt_refmerge_drop_views(schema, identifiers) %}
  {% for identifier in identifiers %}
    {% set relation = adapter.get_relation(database=target.database, schema=schema, identifier=identifier) %}
    {% if relation is not none and relation.is_view %}
      {% do adapter.drop_relation(relation) %}
    {% endif %}
  {% endfor %}
{% endmacro %}
"""

_PROFILE_NAME = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}")


def write_harness_macros(root: Path, profile: str) -> None:
    """dbt_project.yml plus the harness macros; shared by verification runs and cleanup."""
    if not _PROFILE_NAME.fullmatch(profile):
        raise VerificationError(ReasonCode.HARNESS_EMBEDDING_UNSAFE, f"unsupported dbt profile name: {profile!r}")
    (root / "models").mkdir(parents=True, exist_ok=True)
    (root / "macros").mkdir(parents=True, exist_ok=True)
    (root / "dbt_project.yml").write_text(
        f'name: {HARNESS_PROJECT_NAME}\nversion: 1.0.0\nconfig-version: 2\nprofile: "{profile}"\n\n'
        'model-paths: ["models"]\nmacro-paths: ["macros"]\ntarget-path: "target"\nclean-targets: ["target"]\n\n'
        f"models:\n  {HARNESS_PROJECT_NAME}:\n    +materialized: view\n",
        encoding="utf-8",
    )
    (root / "macros" / "generate_schema_name.sql").write_text(GENERATE_SCHEMA_NAME_MACRO, encoding="utf-8")
    (root / "macros" / "dbt_refmerge_query.sql").write_text(QUERY_MACRO, encoding="utf-8")
    (root / "macros" / "dbt_refmerge_drop_views.sql").write_text(DROP_VIEWS_MACRO, encoding="utf-8")


@dataclass(frozen=True)
class HarnessSpec:
    baseline_alias: str
    candidate_alias: str
    baseline_sql: str
    candidate_sql: str


def strip_single_terminal_semicolon(sql: str) -> str:
    s = sql.rstrip()
    if s.endswith(";"):
        body = s[:-1]
        # ensure no second statement: no other semicolon outside strings/comments (approx: no ';' at all)
        if ";" in body.strip():
            raise VerificationError(ReasonCode.HARNESS_EMBEDDING_UNSAFE, "multiple statements in compiled SQL")
        return body
    if ";" in s:
        # interior semicolon -> unsafe
        raise VerificationError(ReasonCode.HARNESS_EMBEDDING_UNSAFE, "semicolon inside compiled SQL")
    return s


def build_harness_project(
    ws: RunWorkspace,
    *,
    profile: str,
    baseline_sql: str,
    candidate_sql: str,
    token: str | None = None,
) -> HarnessSpec:
    token = token or _sanitize_run_token(ws.run_id)
    baseline_alias = f"{BASELINE_ALIAS_PREFIX}{token}"
    candidate_alias = f"{CANDIDATE_ALIAS_PREFIX}{token}"
    for sql in (baseline_sql, candidate_sql):
        # Any "{%" could close the raw block ({%endraw%}, {%- endraw %}, ...); compiled SQL never needs one.
        if "{%" in sql:
            raise VerificationError(ReasonCode.HARNESS_EMBEDDING_UNSAFE, "Jinja block delimiter in compiled SQL")
    baseline_body = strip_single_terminal_semicolon(baseline_sql)
    candidate_body = strip_single_terminal_semicolon(candidate_sql)
    root = ws.harness_project
    write_harness_macros(root, profile)
    (root / "models" / "baseline.sql").write_text(
        HARNESS_MODELS_BASELINE % (baseline_alias, baseline_body), encoding="utf-8"
    )
    (root / "models" / "candidate.sql").write_text(
        HARNESS_MODELS_BASELINE % (candidate_alias, candidate_body), encoding="utf-8"
    )
    return HarnessSpec(
        baseline_alias=baseline_alias,
        candidate_alias=candidate_alias,
        baseline_sql=baseline_body,
        candidate_sql=candidate_body,
    )


def preflight_harness_manifest(
    manifest_path: Path,
    boundary: ScratchBoundary,
) -> tuple[RelationIdentity, RelationIdentity]:
    view = load_manifest(manifest_path)
    wanted = {f"model.{HARNESS_PROJECT_NAME}.baseline", f"model.{HARNESS_PROJECT_NAME}.candidate"}
    nodes = {uid: view.nodes[uid] for uid in wanted if uid in view.nodes}
    if set(nodes) != wanted:
        raise ScratchBoundaryError("harness manifest must contain exactly baseline/candidate nodes")
    allowed = {r.identifier.value for r in boundary.allowed_relations}
    out: list[RelationIdentity] = []
    for uid in sorted(wanted):
        node: ManifestNodeModel = nodes[uid]
        if node.config.get("materialized", "view") != "view":
            raise ScratchBoundaryError(f"harness node not a view: {uid}")
        for hook in ("pre-hook", "post-hook", "pre_hook", "post_hook"):
            if node.config.get(hook):
                raise ScratchBoundaryError(f"harness hooks forbidden: {uid}")
        # dbt-postgres quotes every part, so the manifest spelling is the relation that will be created.
        db = IdentifierIdentity(node.database or "")
        schema = IdentifierIdentity(node.schema_ or "")
        alias_ident = IdentifierIdentity(node.alias or "")
        if db != boundary.database or schema != boundary.schema:
            raise ScratchBoundaryError(f"harness node outside scratch boundary: {uid}")
        if alias_ident.value not in allowed:
            raise ScratchBoundaryError(f"harness alias not allowlisted: {uid}")
        out.append(RelationIdentity(database=db, schema=schema, identifier=alias_ident))
    # reject extra enabled writable nodes
    for uid, node in view.nodes.items():
        if uid not in wanted and node.resource_type in ("model", "seed", "snapshot"):
            cfg = node.config if isinstance(node.config, dict) else {}
            if cfg.get("enabled", True):
                raise ScratchBoundaryError(f"unexpected writable node: {uid}")
    return (out[0], out[1])


def build_verdict_sql(baseline_quoted: str, candidate_quoted: str, columns: list[str], strategy: str) -> str:
    from dbt_refmerge.verification.comparator import (
        generate_except_all_sql,
        generate_grouped_counts_sql,
        quote_ident,
    )

    # columns are raw catalog names; quoting handled inside generators
    _ = quote_ident
    if strategy == "grouped_counts":
        return generate_grouped_counts_sql(baseline_quoted, candidate_quoted, columns)
    return generate_except_all_sql(baseline_quoted, candidate_quoted, columns)


def ledger_relations(ws: RunWorkspace) -> list[RelationIdentity]:
    data = json.loads(ws.ledger_path.read_text())
    out: list[RelationIdentity] = []
    for o in data.get("objects", []):
        out.append(
            RelationIdentity(
                database=IdentifierIdentity(o["database"]),
                schema=IdentifierIdentity(o["schema"]),
                identifier=IdentifierIdentity(o["identifier"]),
            )
        )
    return out
